name: 'Github Action Notification'
description: 'Github Action Notification with Discord and Slack'
author: 'hunghg255'
branding:
  icon: "package"
  color: "gray-dark"

runs:
  using: 'node16'
  main: 'lib/index.js'

inputs:
  discord_webhook:
    description: 'Discord webhook url.'
    required: false
  slack_webhook:
    description: 'Slack webhook url.'
    required: false
  title:
    description: 'Title of notification.'
    required: false
    default: ${{ github.workflow }}
  description:
    description: 'Description of notification.'
    required: false
  status:
    description: "Job status. Should be bound to job.status. Default to success."
    required: false
    default: ${{ job.status }}

